;<?php exit;
[plugin]
class = "Efront\Plugin\ADPhotoSync\Model\ADPhotoSyncPlugin"
name = "ADPhotoSync"
title = "AD Photo Sync"
version = 2.11.0
requires = 5.2.18
compatibility = 5.2.18
author = "Denis Apel"
description = "Synchronisiert Profilbilder der Benutzer aus dem Active Directory in das LMS."
