;<?php exit;
[plugin]
class = "Efront\Plugin\ADPhotoSync\Model\ADPhotoSyncPlugin"
name = "ADPhotoSync"
title = "AD Photo Sync"
version = 2.12.0
requires = 5.2.18
compatibility = 5.2.18
author = "Denis Apel"
description = "Synchronisiert Profilbilder der Benutzer aus dem Active Directory in das LMS. Projektseite und Quellcode: <a href='https://github.com/stardado/ADPhotoSync' target='_blank' rel='noopener'>github.com/stardado/ADPhotoSync</a>"
